FROM openjdk:11
RUN addgroup --system springgroup && adduser springuser --system && usermod -g springgroup springuser
USER springuser:springgroup
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
EXPOSE 9080
ENTRYPOINT ["java","-jar","/app.jar"]