apiVersion: v1
kind: Service
metadata:
  name: hello-spring
spec:
  selector:
    app: hello-spring
  ports:
  - port: 8082
    targetPort: 3100
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-spring
spec:
  selector:
    matchLabels:
      app: hello-spring
  template:
    metadata:
      labels:
        app: hello-spring
    spec:
      containers:
      - name: hello-spring
        image: localhost:32769/helloworld/spring:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
        env:
          - name: ENV_VAR
            value: ENV_VALUE
        livenessProbe:
          httpGet:
            path: /monitor/health/liveness
            port: 9080
          initialDelaySeconds: 60
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /monitor/health/readiness
            port: 9080
          initialDelaySeconds: 60
          periodSeconds: 20