apiVersion: v1
kind: Service
metadata:
  name: reverseproxy-nginx
spec:
  selector:
    app: reverseproxy-nginx
  ports:
  - port: 8083
    targetPort: 7000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy-nginx
spec:
  selector:
    matchLabels:
      app: reverseproxy-nginx
  template:
    metadata:
      labels:
        app: reverseproxy-nginx
    spec:
      containers:
      - name: reverseproxy-nginx
        image: localhost:32769/reverseproxy/nginx:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 7000
        env:
          - name: ENV_VAR
            value: ENV_VALUE
        livenessProbe:
          httpGet:
            path: /monitor/live/
            port: 7000
          initialDelaySeconds: 60
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /monitor/ready/
            port: 7000
          initialDelaySeconds: 60
          periodSeconds: 20