apiVersion: v1
kind: Service
metadata:
  name: hello-node
spec:
  selector:
    app: hello-node
  ports:
  - port: 8081
    targetPort: 3100
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-node
spec:
  selector:
    matchLabels:
      app: hello-node
  template:
    metadata:
      labels:
        app: hello-node
    spec:
      containers:
      - name: hello-node
        image: localhost:32769/helloworld/nodejs:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3100
        env:
          - name: ENV_VAR
            value: ENV_VALUE
        livenessProbe:
          httpGet:
            path: /monitor/live
            port: 3100
          initialDelaySeconds: 60
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /monitor/ready
            port: 3100
          initialDelaySeconds: 60
          periodSeconds: 20