spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include:
        - "*"
