apiVersion: v1
kind: Service
metadata:
  name: hello-flask
spec:
  selector:
    app: hello-flask
  ports:
  - port: 8080
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-flask
spec:
  selector:
    matchLabels:
      app: hello-flask
  template:
    metadata:
      labels:
        app: hello-flask
    spec:
      containers:
      - name: hello-flask
        image: localhost:32769/helloworld/flask:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: ENV_VAR
            value: ENV_VALUE
        livenessProbe:
          httpGet:
            path: /monitor/health/live
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /monitor/health/ready
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 20